site_name: Le Jeu de Trictrac rendu facile
site_author: Henri Bourcereau
site_url: https://mmai.github.io/leJeuDeTrictracRenduFacile/

# repository
repo_url: https://github.com/mmai/leJeuDeTrictracRenduFacile/
repo_name: code source
edit_uri: "" # disable edit button linking to repository

# files paths
docs_dir: src/
site_dir: html/

nav:
  - Présentation: index.md
  - Préface: tome1/preface.md
  - Avertissement: tome1/avertissement.md
  - Introduction: tome1/introduction.md
  - Section 1: tome1/section1.md
  - Section 2: tome1/section2.md
  - Section 3: tome1/section3.md
  - Section 4: tome2/section4.md
  - Section 5: tome2/section5.md

# -----  Config for Material theme ------
theme:
  name: material
  language: fr
  features:
    # - announce.dismiss
    # - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  analytics:
    gtag: G-7P8EEWM1YZ
extra:
  analytics:
    provider: google
    property: G-7P8EEWM1YZ
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/mmai
      - icon: fontawesome/brands/mastodon
        link: https://mamot.fr/@mmai
# ----- Config for Readthedoc theme ------
# theme:
  # name: readthedocs
  # analytics:
  #   gtag: G-7P8EEWM1YZ
